export const demoSpecialties = [
  { id: 1, nombre: 'Cardiologia' },
  { id: 2, nombre: 'Dermatologia' },
  { id: 3, nombre: 'Neurologia' },
  { id: 4, nombre: 'Kinesiologia' },
]

export const demoBoxes = [
  {
    id: 1,
    numero: 'B-201',
    piso: 2,
    sector: 'Ala Norte',
    especialidad_id: 1,
    especialidad: { nombre: 'Cardiologia' },
    equipamiento: ['Electrocardiógrafo', 'Camilla Clínica', 'PC Ficha'],
    estado: 'disponible',
    medico: null,
    proximoMedico: 'Dra. Elena Rios (14:00 hrs)',
  },
  {
    id: 2,
    numero: 'B-202',
    piso: 2,
    sector: 'Ala Norte',
    especialidad_id: 1,
    especialidad: { nombre: 'Cardiologia' },
    equipamiento: ['Monitor Multiparámetro', 'Camilla', 'PC Ficha'],
    estado: 'en_atencion',
    medico: 'Dr. Pablo Mena',
    atencion: { id: 'demo-active-2', medico_id: 2, hora_entrada: new Date(Date.now() - 12 * 60000).toISOString() },
    horaEntrada: new Date(Date.now() - 12 * 60000).toISOString(),
    proximoMedico: 'Dr. Felipe Mena (15:30 hrs)',
  },
  {
    id: 3,
    numero: 'B-203',
    piso: 2,
    sector: 'Ala Norte',
    especialidad_id: 1,
    especialidad: { nombre: 'Cardiologia' },
    equipamiento: ['Ecográfo Doppler', 'PC Ficha'],
    estado: 'fuera_servicio',
    medico: null,
  },
  {
    id: 4,
    numero: 'B-301',
    piso: 3,
    sector: 'Ala Sur',
    especialidad_id: 2,
    especialidad: { nombre: 'Dermatologia' },
    equipamiento: ['Dermatoscopio Digital', 'Lámpara Wood', 'PC Ficha'],
    estado: 'disponible',
    medico: null,
    proximoMedico: 'Dra. Paula Silva (14:15 hrs)',
  },
  {
    id: 5,
    numero: 'B-302',
    piso: 3,
    sector: 'Ala Sur',
    especialidad_id: 2,
    especialidad: { nombre: 'Dermatologia' },
    equipamiento: ['Camilla Procedimientos', 'Lupa UV', 'PC Ficha'],
    estado: 'disponible',
    medico: null,
  },
  {
    id: 6,
    numero: 'B-303',
    piso: 3,
    sector: 'Ala Sur',
    especialidad_id: 2,
    especialidad: { nombre: 'Dermatologia' },
    equipamiento: ['Electrocauterio', 'Lámpara LED', 'PC Ficha'],
    estado: 'en_atencion',
    medico: 'Dra. Paula Silva',
    atencion: { id: 'demo-active-6', medico_id: 5, hora_entrada: new Date(Date.now() - 27 * 60000).toISOString() },
    horaEntrada: new Date(Date.now() - 27 * 60000).toISOString(),
  },
  {
    id: 7,
    numero: 'B-401',
    piso: 4,
    sector: 'Ala Oriente',
    especialidad_id: 3,
    especialidad: { nombre: 'Neurologia' },
    equipamiento: ['Electroencefalógrafo', 'Martillo Reflejos', 'PC Ficha'],
    estado: 'disponible',
    medico: null,
  },
  {
    id: 8,
    numero: 'B-402',
    piso: 4,
    sector: 'Ala Oriente',
    especialidad_id: 3,
    especialidad: { nombre: 'Neurologia' },
    equipamiento: ['Camilla Exploración', 'PC Ficha'],
    estado: 'en_atencion',
    medico: 'Dr. Mateo Cruz',
    atencion: { id: 'demo-active-8', medico_id: 7, hora_entrada: new Date(Date.now() - 6 * 60000).toISOString() },
    horaEntrada: new Date(Date.now() - 6 * 60000).toISOString(),
  },
  {
    id: 9,
    numero: 'B-403',
    piso: 4,
    sector: 'Ala Oriente',
    especialidad_id: 3,
    especialidad: { nombre: 'Neurologia' },
    equipamiento: ['Camilla', 'PC Ficha'],
    estado: 'disponible',
    medico: null,
  },
  {
    id: 10,
    numero: 'B-101',
    piso: 1,
    sector: 'Gimnasio Kine',
    especialidad_id: 4,
    especialidad: { nombre: 'Kinesiologia' },
    equipamiento: ['Ultrasonido Terapéutico', 'Camilla Kine', 'Espalderas'],
    estado: 'disponible',
    medico: null,
    proximoMedico: 'Kinesióloga Valentina Soto (14:00 hrs)',
  },
  {
    id: 11,
    numero: 'B-102',
    piso: 1,
    sector: 'Gimnasio Kine',
    especialidad_id: 4,
    especialidad: { nombre: 'Kinesiologia' },
    equipamiento: ['TENS / Electroterapia', 'Camilla Kine', 'Balones Bobath'],
    estado: 'disponible',
    medico: null,
  },
]

export const demoDoctors = [
  { id: 1, nombre: 'Dra. Elena Rios', tipo: 'medico', especialidad_id: 1, especialidad_nombre: 'Cardiologia' },
  { id: 2, nombre: 'Dr. Pablo Mena', tipo: 'medico', especialidad_id: 1, especialidad_nombre: 'Cardiologia' },
  { id: 3, nombre: 'Dra. Camila Rojas', tipo: 'medico', especialidad_id: 2, especialidad_nombre: 'Dermatologia' },
  { id: 4, nombre: 'Dr. Nicolas Vera', tipo: 'medico', especialidad_id: 2, especialidad_nombre: 'Dermatologia' },
  { id: 5, nombre: 'Dra. Paula Silva', tipo: 'medico', especialidad_id: 2, especialidad_nombre: 'Dermatologia' },
  { id: 6, nombre: 'Dra. Irene Soto', tipo: 'medico', especialidad_id: 3, especialidad_nombre: 'Neurologia' },
  { id: 7, nombre: 'Dr. Mateo Cruz', tipo: 'medico', especialidad_id: 3, especialidad_nombre: 'Neurologia' },
  { id: 8, nombre: 'Kinesióloga Valentina Soto', tipo: 'kinesiologo', especialidad_id: 4, especialidad_nombre: 'Kinesiologia' },
  { id: 9, nombre: 'Kinesiólogo Diego Perez', tipo: 'kinesiologo', especialidad_id: 4, especialidad_nombre: 'Kinesiologia' },
]
